apiVersion: v1
kind: Service
metadata:
  name: codification-ape-model-service-test-pytorch-wrapper
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: codification-ape-model-deployment-test-pytorch-wrapper
