apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-dev-meta-rev2
spec:
  project: default
  source:
    repoURL: https://github.com/InseeFrLab/codif-ape-cd.git
    targetRevision: main
    path: api-meta-rev2
  destination:
    server: https://kubernetes.default.svc
    namespace: projet-ape
  syncPolicy:
    automated:
      selfHeal: true
