apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etl-sampling
spec:
  project: default
  source:
    repoURL: https://github.com/InseeFrLab/codif-ape-API.git
    targetRevision: HEAD
    path: etl-sampling
  destination:
    server: https://kubernetes.default.svc
    namespace: projet-ape
  syncPolicy:
    automated:
      selfHeal: true