apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codification-ape-model-ingress-pytorch
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - codification-ape-pytorch.lab.sspcloud.fr
  rules:
    - host: codification-ape-pytorch.lab.sspcloud.fr
      http:
        paths:
          - path: /2008(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: codification-ape-model-service-pytorch2008
                port:
                  number: 80
          - path: /2025(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: codification-ape-model-service-pytorch2025
                port:
                  number: 80
