# Creating MLflow deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codification-ape-rag-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codification-ape-rag-ui
  template:
    metadata:
      labels:
        app: codification-ape-rag-ui
    spec:
      containers:
        - name: codif-ape-rag-ui
          image: meilametayebjee/codification-ape-graph-rag-streamlit:v0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: my-s3-creds
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-s3-creds
                  key: secretKey
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: NEO4J_API_KEY
              valueFrom:
                secretKeyRef:
                  name: neo4j
                  key: apiKey
          resources:
            limits:
              cpu: 30000m
              memory: 50Gi
            requests:
              cpu: 100m
              memory: 1Gi
